#!/bin/bash

export PATH="/usr/X11/bin:$PATH" # so I can continue using `lndir` until Apple gets rid of X11 tools altogether

configs_dir=$(dirname $0)
if [ $(echo $0 | cut -c1) = "/" ]; then
	configs_dir=$(dirname $0)
else
  configs_dir=$(pwd)/$(echo $0 | sed -e s/\\.\\/install//)
fi

echo "Linking $configs_dir to $HOME"
lndir -silent $configs_dir $HOME

rm $HOME/install  # Don't want install script hanging around
rm -rf $HOME/TextMate
rm -rf $HOME/Terminal.app
rm -rf $HOME/.git     # Don't need the git repo in $HOME

homedir_files=".vim/.vimrc .zsh/.zshrc .zsh/.zshenv"

for extra in $homedir_files; do
  name=$(basename $extra)
  orig=$configs_dir/$extra

  if [[ ! -h $HOME/$name ]]; then
    ln -s $orig $HOME/$name
  fi
done

app_support_files="TextMate Vico"

for extra in $app_support_files; do
  name=$(basename $extra)
  orig=$configs_dir/$extra
  app_support="$HOME/Library/Application Support"

  if [[ ! -d $app_support/$extra ]]; then
    ln -s $orig "$app_support/$extra"
  fi
done

if [ ! -f ~/Library/Preferences/com.googlecode.iterm2.plist ]; then
  cp iTerm2/com.googlecode.iterm2.plist ~/Library/Preferences/
fi
